# My bash config for macOS
#  ／l、
#（ﾟ､ ｡７
#⠀ l、ﾞ~ヽ 
#  じし(_,)ノ

#########################################

## Default stuff 💾
export EDITOR="/usr/local/bin/nvim"

## Cowsay 🍔
fortune -s | cowsay -f moose | lolcat --seed=100

## Starship 🚀
eval "$(starship init bash)"

## Aliases 🔥

# Bash 🐚
alias bashconfig="/usr/local/bin/nvim $HOME/.bashrc"
alias reloadbash="source $HOME/.bashrc"

# Sudo -s instead of su and sudo 🦸
aliases['su'] = 'sudo -s'
aliases['sudo'] = 'sudo -s'

# Tree/List 🌲
alias ls="exa -Ga --icons"
alias tree="exa -1aT --icons"

# Make parent dir with mkdir 👴
alias mkdir="mkdir -pv"

# Safety 😷
alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"
alias ln="ln -i"
