# My Zsh config for macOS
#  ／l、
#（ﾟ､ ｡７
#⠀ l、ﾞ~ヽ 
#  じし(_,)ノ

#########################################

## Default stuff 💾
export EDITOR="/usr/local/bin/nvim"

## Syntax 🌈
source /usr/local/share/zsh-syntax-highlighting/zsh-syntax-highlighting.zsh

## Cowsay 🍔
fortune -s | cowsay -f moose | lolcat --seed=100

## Starship 🚀
eval "$(starship init zsh)"

## Aliases 🔥

# Zsh 🦀
alias zshconfig="/usr/local/bin/nvim $HOME/.zshrc"
alias reloadzsh="source $HOME/.zshrc"

# Sudo -s instead of su and sudo 🦸
aliases['su'] = 'sudo -s'
aliases['sudo'] = 'sudo -s'

# Tree/List 🌲
alias ls="exa -Ga --icons"
alias tree="exa -1aT --icons"

# Make parent dir with mkdir 👴
alias mkdir="mkdir -pv"

# Safety 😷
alias mv="mv -i"
alias cp="cp -i"
alias rm="rm -i"
alias ln="ln -i"
